bsadmin/urls.py
from django.urls import path

from bsadmin.views import *

app_name = 'bsadmin'
urlpatterns = [
    path('', faculty_index, name='index'),
    path('transcript/search/', at_search, name='at-search'),
    path('transcript/faculty/<int:faculty_id>/category/', faculty_transcript_category,
         name='faculty-transcript-category'),
    path('transcript/<int:faculty_id>/reports/', ReportFacultyRegAcademicTranscript.as_view(),
         name='faculty-academic-transcript-reports'),
    path('transcript/faculties/reports/', ReportAllFacultyRegAcademicTranscript.as_view(),
         name='all-faculty-academic-transcript-reports'),
    path('transcript/faculty/<int:faculty_id>/category/<category_id>/', registration_academic_transcript_faculty,
         name='academic-transcript-faculty-registration'),

    path('transcript/student/', registration_academic_transcript_student, name='academic-transcript-student'),
    path('faculty/', faculty, name='faculty'),
    path('faculty/<int:faculty_id>/specialities/', speciality, name='speciality'),

    path('transcript/save-student/', save_academic_transcript_student, name='save-student-academic-transcript'),

    path('faculty/update/<int:id>/transcript/', update_faculty_transcript, name='update_faculty_transcript'),
    path('faculty/delete/<int:id>/transcript/', delete_faculty_transcript, name='delete_faculty_transcript'),
    path('faculty/delete/<int:id>/history/transcript/', delete_registry_faculty_transcript,
         name='delete_faculty_history_transcript'),

    path('fail/transcript/', fail_transcript, name='fail_transcript'),
    path('faculty/specialities/', specialities_by_faculty, name='specialities-faculty'),

]

core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bsheet/', include('bsadmin.urls'), name='bsheet'),
    path('stepper/', include('stepper.urls'), name='stepper'),
    path('integrator/', include('integrator.urls'), name='integrator'),
    path('archive/', include('archives.urls'), name='archive'),
    path('', include('student.urls'), name='student'),
]
# urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]
if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)), ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/teachers/transcripts/academictranscript_all_faculty_report.html
{% extends 'admin_base.html' %}
{% load static i18n crispy_forms_tags cms_tags %}


{% block content %}
    <div class="container">
        {% if CUSTOM_ROLES.SPEC in DB_ROLES %}
            <h4 class="mb-4 text-center">{% trans 'Общий отчет по академическим справкам всех факультетов' %}</h4>
            <hr/>
            <a class="add_tabledata addBtn btn btn-danger btn-sm"
               href="{% url 'bsadmin:index' %}">
                <i class="fa fa-arrow-left"></i> {% trans 'Назад' %}
            </a>
            <hr/>
            <div class="table-responsive">

                <table class="table table-bordered table-sm table-responsive-md">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">{% trans '№ академической справки' %}</th>
                        <th scope="col">{% trans 'ФИО студента' %}</th>
                        <th scope="col">{% trans 'Факультет' %}</th>
                        <th scope="col">{% trans 'Специальность' %}</th>
                        <th scope="col">{% trans 'Дата получения' %}</th>
                    </tr>
                    </thead>
                    <tbody class="order">
                    {% for report in regtranscripts %}
                        <tr data-id="{{ report.id }}">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ report.faculty_transcript.transcript_number }}</td>
                            <td>{{ report.student_fio }}</td>
                            <td>{{ report.faculty_history|default_if_none:"-" }}</td>
                            <td>{{ report.speciality_history|default_if_none:"-" }}</td>
                            <td>{{ report.create_date|date:"d-m-Y" }}</td>
                        </tr>
                    {% empty %}
                        <tr class="table-warning nosort">
                            <td colspan="100%" class="text-center">
                                <small class="text-muted">{% trans 'Пусто' %}</small>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% include "utils/_pagination.html" with page_obj=regtranscripts %}
            </div>
        {% else %}
           {% include 'utils/_access.html' %}
        {% endif %}
    </div>

{% endblock %}

templates/teachers/transcripts/academictranscript_category.html
{% extends 'admin_base.html' %}
{% load static i18n crispy_forms_tags cms_tags %}


{% block content %}
    <div class="container">
        {% if CUSTOM_ROLES.SPEC in DB_ROLES %}
            <h4 class="mb-0 text-center">{{ faculty.title }}({{ faculty.short_name }})</h4>
            <hr/>
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <a class="add_tabledata addBtn btn btn-danger btn-sm"
                       href="{% url 'bsadmin:index' %}">
                        <i class="fa fa-arrow-left"></i> {% trans 'Список факультетов' %}
                    </a>
                    <a class="add_tabledata addBtn btn btn-success btn-sm mx-2"
                       href="{% url 'bsadmin:faculty-academic-transcript-reports' faculty_id=faculty.id %}">
                        <i class="fas fa-flag"></i> {% trans 'Отчёт' %}
                    </a>
                </div>

                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#uploadModal">
                    Справка была повреждена ?
                </button>
            </div>
            <hr/>
            <div class="row">
                {% for category in category_list %}
                    {% if category.category == faculty.category %}
                        <div class="col-md-3 mb-2">
                            <div class="card">
                                <div class="card-body">
                                    <a href="{% url 'bsadmin:academic-transcript-faculty-registration' faculty_id=faculty.id category_id=category.id %}">
                                        <h6 class="card-title mb-0">{{ category.title }} - количество
                                            листов: {{ category.page_count }}</h6>
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>

            <hr/>
            <h4 class="text-center">Список академических справок</h4>

            <hr/>
            {% include 'utils/_messages.html' %}
            <div class="table-responsive">
                <table class="table table-bordered table-sm table-responsive-md">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Категория</th>
                        <th scope="col">
                            <a href="?sort={% if request.GET.sort == 'is_used' %}-is_used{% else %}is_used{% endif %}&page={{ request.GET.page|default:"1" }}">
                                Номер справки
                                {% if request.GET.sort == 'is_used' %}
                                    <i class="fa fa-sort-up"></i>
                                {% elif request.GET.sort == '-is_used' %}
                                    <i class="fa fa-sort-down"></i>
                                {% else %}
                                    <i class="fa fa-sort"></i>
                                {% endif %}
                            </a>

                        </th>
                        <th scope="col">Повреждена ?</th>
                    </tr>
                    </thead>
                    <tbody class="order">
                    {% for transcript in transcripts %}
                        <tr class="{% if transcript.is_defective %} error-block {% endif %} {% if transcript.is_used %} success-block {% endif %}"
                            data-id="{{ transcript.id }}">
                            <td>{{ forloop.counter0|add:transcripts.start_index }}</td>
                            <td>
                                {% if transcript.is_used %}
                                    <button class="btn btn-outline-danger btn-sm delete-ft-button"
                                            data-id="{{ transcript.id }}">
                                        <i class="fas fa-trash-alt"></i>
                                    </button>
                                {% endif %}
                                {{ transcript.category.title }} (лист: {{ transcript.category.page_count }})
                            </td>
                            <td>
                                {{ transcript.transcript_number }}
                                {% if transcript.is_used %}
                                    <i class="fas fa-check-square"></i>
                                {% endif %}

                                {% if transcript.is_defective %}
                                    <i class="fas fa-times"></i>
                                {% endif %}
                            </td>
                            <td>
                                {% if transcript.is_defective and transcript.files %}
                                    <a href="{{ transcript.files.url }}" target="_blank"><i class="fas fa-file-pdf"></i></a>
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                {% include "utils/_pagination.html" with page_obj=transcripts %}
            </div>
        {% else %}
            {% include 'utils/_access.html' %}
        {% endif %}
    </div>

    <!-- Модальное окно -->
    <div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="uploadModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="uploadModalLabel">Повреждена справка?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="uploadForm" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="transcript_number">Введите № академической справки*</label>
                            <input type="text" class="form-control form-control-sm" id="transcript_number"
                                   name="transcript_number"
                                   required>
                        </div>
                        <div class="form-group">
                            <label for="files">Загрузить файл</label>
                            <input type="file" class="form-control form-control-sm" id="files" name="files" required>
                        </div>

                        <div id="error-message" class="alert alert-danger d-none">

                            <span id="error-text"></span>
                        </div>

                        <div id="not-found-message" class="alert alert-warning d-none">

                            <span id="not-found-text"></span>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Закрыть</button>
                        <button type="submit" class="btn btn-sm btn-primary">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Модальное окно для подтверждения удаления -->
    <div class="modal fade" id="deleteFacultyTranscriptModal" tabindex="-1" role="dialog"
         aria-labelledby="deleteFacultyTranscriptModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteFacultyTranscriptModalLabel">Подтвердите удаление</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Вы уверены, что хотите удалить запись:</p>
                    <h5><strong>Справку №:</strong> <span id="deleteTranscriptNumber"></span></h5>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Отмена</button>
                    <button type="button" class="btn btn-sm btn-danger" id="confirmFTDelete">Удалить</button>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#myedu_id').focus().val('');

            $("#uploadForm").submit(function (event) {
                event.preventDefault();

                var formData = new FormData(this);


                $("#error-message").addClass("d-none");
                $("#not-found-message").addClass("d-none");


                $("#error-text").text("");
                $("#not-found-text").text("");

                $.ajax({
                    url: "{% url 'bsadmin:fail_transcript' %}",
                    type: "POST",
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (response) {
                        if (response.success) {
                            toastr["success"]("Данные успешно занесены в базу");
                            location.reload();
                        } else if (response.error) {
                            $("#error-text").text(response.error);
                            $("#error-message").removeClass("d-none");
                        } else if (response.not_found) {
                            $("#not-found-text").text(response.not_found);
                            $("#not-found-message").removeClass("d-none");
                        }
                    },
                    error: function () {
                        $("#error-text").text("Произошла ошибка. Попробуйте снова.");
                        $("#error-message").removeClass("d-none");
                    }
                });
            });

            var rowToDelete = null;


            $('.delete-ft-button').on('click', function () {
                rowToDelete = $(this).closest('tr');

                var transcriptNumber = rowToDelete.find('td').eq(2).text();

                $('#deleteTranscriptNumber').text(transcriptNumber);
                $('#deleteFacultyTranscriptModal').modal('show');
            });


            $('#confirmFTDelete').on('click', function () {
                var id = rowToDelete.data('id');
                $.ajax({
                    url: '/bsheet/faculty/delete/' + id + '/history/transcript/',
                    type: 'DELETE',
                    success: function (response) {
                        if (response.status === 'success') {
                            $('#deleteFacultyTranscriptModal').modal('hide');
                            toastr["success"](response.message);
                            location.reload()
                        } else {
                            toastr["error"](response.message);
                        }
                    },
                    error: function () {
                        toastr["error"]('Повторите попытку!');
                    }
                });
            });
        });
    </script>
{% endblock %}

templates/teachers/transcripts/academictranscript_student.html
{% extends 'admin_base.html' %}
{% load static i18n crispy_forms_tags cms_tags %}


{% block content %}
    <!-- Индикатор загрузки -->
    <div id="loading-overlay" style="
        display: none;
        position: fixed;
        top: 0; left: 0;
        width: 100%; height: 100%;
        background: rgba(0,0,0,0.4);
        z-index: 9999;
        text-align: center;
        color: white;
        font-size: 24px;
        padding-top: 20%;
    ">
        <i class="fas fa-spinner fa-spin"></i> Загрузка...
    </div>
    <div class="container">
        {% if CUSTOM_ROLES.SPEC in DB_ROLES %}

            <form action="" method="post" class="mb-4" id="search-form">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-md-6">
                        <input type="text" class="form-control" placeholder="ФИО или уникальный номер студента"
                               name="student" id="myedu_id"/>
                    </div>
                    <div class="col-md-4">
                        <button type="submit" name="search_myedu"
                                class="btn btn-danger mt-2 mt-md-0">{% trans 'Поиск из MyEDU' %}</button>
                    </div>
                </div>
                <div class="my-2">
                    <label>
                        Если студент отсутствует в MyEDU
                        <input type="checkbox" name="manual_entry" id="manual_entry"
                               {% if manual_entry_checked %}checked{% endif %}/>
                    </label>
                </div>
                <div class="form-row" id="custom_transcript_student"
                     style="display: {% if manual_entry_checked %}flex{% else %}none{% endif %};">

                    <div class="col-md-6">
                        <label for="custom_faculty" class="form-label">Выберите факультет</label>
                        <select class="form-control" aria-label="" id="custom_faculty" name="custom_faculty_id">
                            <option selected value=''>----------</option>
                            {% for faculty in faculties %}
                                <option value="{{ faculty.id }}"
                                        {% if faculty.id|stringformat:"s" == custom_data.custom_faculty_id %}selected{% endif %}>
                                    {{ faculty.title }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-6">
                        <label for="custom_speciality" class="form-label">Выберите специальность</label>
                        <select class="form-control" aria-label="" id="custom_speciality" name="custom_speciality_id">
                            <option selected value=''>----------</option>
                            {% for speciality in custom_data.specialities %}
                                <option value="{{ speciality.id }}"
                                        {% if speciality.id|stringformat:"s" == custom_data.custom_speciality_id %}selected{% endif %}>
                                    {{ speciality.title }} ({{ speciality.code|default_if_none:"" }})
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-6">
                        <label for="custom_student_fio" class="form-label">Введите ФИО студента</label>
                        <input type="text" class="form-control" id="custom_student_fio" name="custom_student_fio"
                               placeholder="Асанов Асан Асанович"
                               value="{{ custom_data.custom_student_fio|default_if_none:'' }}">
                    </div>
                    <div class="col-md-6">
                        <label for="custom_transcript_number" class="form-label">№ академической справки</label>
                        <input type="text" class="form-control" id="custom_transcript_number"
                               name="custom_transcript_number"
                               placeholder="123456789"
                               value="{{ custom_data.custom_transcript_number|default_if_none:'' }}">
                    </div>

                    <input type="hidden" name="custom_faculty_title" id="custom_faculty_title"
                           value="{{ custom_faculty_title|default_if_none:'' }}"/>
                    <input type="hidden" name="custom_speciality_title" id="custom_speciality_title"
                           value="{{ custom_speciality_title|default_if_none:'' }}"/>

                    <div class="my-3 text-center col-md-12">
                        <button type="submit" class="btn btn-danger">Сохранить</button>
                    </div>
                </div>

            </form>
            {% include 'utils/_messages.html' %}
            {% if students %}
                <div class="row my-4">
                    {% for student in students %}
                        <div class="col-md-6 mb-2">
                            <div class="card h-100 d-flex flex-column">
                                <div class="card-body flex-grow-1">

                                    <form action="{% url 'bsadmin:save-student-academic-transcript' %}" method="post">
                                        {% csrf_token %}
                                        <h5 class="card-title mb-0">{{ student.student_fio }}</h5>
                                        <p class="card-text">
                                            Факультет: {{ student.faculty_name }} <br/>
                                            Специальность: {{ student.speciality_name }}
                                        </p>
                                        <input type="hidden" value="{{ student.student_id }}" name="student_id">
                                        <input type="hidden" value="{{ student.student_fio }}" name="student_fio">
                                        <input type="hidden" value="{{ student.faculty_id }}" name="faculty_id">
                                        <input type="hidden" value="{{ student.faculty_name }}" name="faculty_title">
                                        <input type="hidden" value="{{ student.speciality_name }}"
                                               name="speciality_title">
                                        <input type="hidden" value="{{ student.speciality_id }}" name="speciality_id">
                                        <div class="form-row">
                                            <div class="col-md-9">
                                                <input type="text"
                                                       class="form-control transcript_number"
                                                       name="transcript_number"
                                                       placeholder="Номер академической справки"
                                                />
                                            </div>
                                            <div class="col-md-3">
                                                <button type="submit" class="btn btn-danger">Сохранить</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% else %}
            {% include 'utils/_access.html' %}
        {% endif %}
    </div>
{% endblock %}
{% block scripts %}
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function () {
            $('#myedu_id').focus().val('');

            const observer = new MutationObserver(() => {
                let input = $('.transcript_number:first');
                if (input.length) {
                    input.focus();
                    observer.disconnect();
                }
            });

            observer.observe(document.body, {childList: true, subtree: true});

            $('#manual_entry').change(function () {
                if ($(this).is(':checked')) {
                    $('#custom_transcript_student').css('display', 'flex');
                } else {
                    $('#custom_transcript_student').css('display', 'none');
                }
            });

            document.getElementById('search-form').addEventListener('submit', function (e) {
                const btn = document.getElementById('search-btn');
                const overlay = document.getElementById('loading-overlay');

                // Показываем оверлей и блокируем все
                overlay.style.display = 'block';
                btn.disabled = true;

                // Можно заблокировать всю страницу кликами
                document.body.style.pointerEvents = 'none';
                overlay.style.pointerEvents = 'auto';
            });

            $("#custom_faculty_title").val($("#custom_faculty option:selected").text());
            $("#custom_faculty").on('change', function () {
                $("#custom_faculty_title").val($("#custom_faculty option:selected").text());
                let faculty_id = this.value;
                let speciality = $("#custom_speciality");
                speciality.empty();
                speciality.append("<option selected value=''>------------</option>");
                $.ajax({
                    type: "GET",
                    data: {"faculty_id": faculty_id},
                    url: "{% url 'bsadmin:specialities-faculty' %}",
                    success: function (data) {
                        data.specialities.forEach(function (spec) {
                            speciality.append($("<option>", {
                                value: spec.id,
                                text: spec.title + " (" + spec.code + ")"
                            }));
                        });
                    },
                    error: function (err) {
                        alert("Ошибка при получении специальности")
                    }
                })
            });

            $("#custom_speciality_title").val($("#custom_speciality option:selected").text());
            $("#custom_speciality").on("change", function () {
                $("#custom_speciality_title").val($("#custom_speciality option:selected").text());
            });
        });
    </script>
{% endblock %}

templates/teachers/transcripts/index.html
{% extends 'admin_base.html' %}
{% load static i18n crispy_forms_tags cms_tags %}


{% block content %}
    <div class="container">
        <h4 class="text-center mb-0">Модуль#1: Академическая справка</h4>
        <hr/>
        {% if CUSTOM_ROLES.SPEC in DB_ROLES %}
            {% include 'utils/_messages.html' %}
            <div class="row">
                <div class="col-md-8">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-md-8">
                                <label for="transcript_number" class="form-label">Введите № академической справки для
                                    проверки</label>
                                <input type="text" class="form-control form-control-sm" id="custom_transcript_number"
                                       name="transcript_number" placeholder="12345678"/>
                            </div>
                            <div class="col-md-2">
                                <input type="submit" class="btn btn-sm btn-danger mt-md-4 mt-2" value="Поиск"/>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-4">
                    <div class="mt-md-4 text-right">
                        <a href="{% url 'bsadmin:all-faculty-academic-transcript-reports' %}"
                           class="btn btn-sm btn-success">Общий
                            отчёт</a>
                    </div>
                </div>
            </div>
            <hr/>
            <h4 class="text-center mb-0">{% trans 'Список факультетов' %}</h4>
            <hr/>
            <div class="row">
                {% for faculty in faculties %}
                    <div class="col-md-3 mb-2">
                        <div class="card h-100 d-flex flex-column">
                            <div class="card-body flex-grow-1">
                                <a href="{% url 'bsadmin:faculty-transcript-category' faculty_id=faculty.id %}">
                                    <h6 class="card-title mb-0">{{ faculty.title }} ({{ faculty.short_name }})</h6>
                                </a>
                                {% trans 'Зарегистр. справки:' %} {{ faculty.total_documents }} <br/>
                                {% trans 'Использванные справки:' %} {{ faculty.used_documents }} <br/>
                                {% trans 'Бракованные справки:' %} {{ faculty.defective_documents }} <br/>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            {% include 'utils/_access.html' %}
        {% endif %}
    </div>
{% endblock %}
{% block scripts %}
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function () {
            $('#custom_transcript_number').focus().val('');
        });
    </script>
{% endblock %}