bsadmin/urls.py
from django.urls import path

from bsadmin.views import *

app_name = 'bsadmin'
urlpatterns = [
    path('', faculty_index, name='index'),
    path('transcript/search/', at_search, name='at-search'),
    path('transcript/faculty/<int:faculty_id>/category/', faculty_transcript_category,
         name='faculty-transcript-category'),
    path('transcript/<int:faculty_id>/reports/', ReportFacultyRegAcademicTranscript.as_view(),
         name='faculty-academic-transcript-reports'),
    path('transcript/faculties/reports/', ReportAllFacultyRegAcademicTranscript.as_view(),
         name='all-faculty-academic-transcript-reports'),
    path('transcript/faculty/<int:faculty_id>/category/<category_id>/', registration_academic_transcript_faculty,
         name='academic-transcript-faculty-registration'),

    path('transcript/student/', registration_academic_transcript_student, name='academic-transcript-student'),
    path('faculty/', faculty, name='faculty'),
    path('faculty/<int:faculty_id>/specialities/', speciality, name='speciality'),

    path('transcript/save-student/', save_academic_transcript_student, name='save-student-academic-transcript'),

    path('faculty/update/<int:id>/transcript/', update_faculty_transcript, name='update_faculty_transcript'),
    path('faculty/delete/<int:id>/transcript/', delete_faculty_transcript, name='delete_faculty_transcript'),
    path('faculty/delete/<int:id>/history/transcript/', delete_registry_faculty_transcript,
         name='delete_faculty_history_transcript'),

    path('fail/transcript/', fail_transcript, name='fail_transcript'),
    path('faculty/specialities/', specialities_by_faculty, name='specialities-faculty'),

]

core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bsheet/', include('bsadmin.urls'), name='bsheet'),
    path('stepper/', include('stepper.urls'), name='stepper'),
    path('integrator/', include('integrator.urls'), name='integrator'),
    path('archive/', include('archives.urls'), name='archive'),
    path('', include('student.urls'), name='student'),
]
# urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]
if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)), ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/teachers/base/faculty.html
{% extends 'admin_base.html' %}
{% load static i18n %}


{% block content %}
    <div class="container">
        {% if CUSTOM_ROLES.ADMIN in DB_ROLES %}
            {% include 'utils/_messages.html' %}
            <form method="post" action="">
                {% csrf_token %}

                <button type="submit" class="btn btn-sm btn-danger">{% trans 'Синхронизировать' %}</button>
            </form>
            <hr/>
        {% endif %}
        {% if CUSTOM_ROLES.SPEC in DB_ROLES %}
            <h3 class="text-center my-2">{% trans 'Список факультетов' %}</h3>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">{% trans 'Название' %}</th>
                        <th scope="col">{% trans 'Короткое' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for faculty in faculties %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>
                                <a href="{% url 'bsadmin:speciality' faculty_id=faculty.id %}">
                                    {{ faculty.title }}
                                </a>
                            </td>
                            <td>{{ faculty.short_name }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="3" class="text-center">{% trans 'Нет данных' %}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
           {% include 'utils/_access.html' %}
        {% endif %}
    </div>
{% endblock %}

templates/teachers/base/speciality.html
{% extends 'admin_base.html' %}
{% load static i18n %}


{% block content %}
    <div class="container">
        {% include 'utils/_messages.html' %}
        <div class="d-flex flex-wrap">
            <div class="mb-md-0 mb-2">
                <a href="{% url 'bsadmin:faculty' %}" class="btn btn-sm btn-danger mr-2">
                    <i class="fa fa-arrow-left"></i> Список факультетов
                </a>
            </div>
            {% if CUSTOM_ROLES.ADMIN in DB_ROLES %}

                <form method="post" action="">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-danger">{% trans 'Синхронизировать' %}</button>
                </form>

            {% endif %}
        </div>

        <hr/>
        {% if CUSTOM_ROLES.SPEC in DB_ROLES %}
            <h4 class="mb-3">{% trans 'Список специальностей факультета' %} "{{ faculty.title }}"</h4>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">{% trans 'Название' %}</th>
                        <th scope="col">{% trans 'Код' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for speciality in specialities %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ speciality.title }}</td>
                            <td>{{ speciality.code|default:"-" }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="3" class="text-center">{% trans 'Нет данных' %}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            {% include 'utils/_access.html' %}
        {% endif %}
    </div>
{% endblock %}