archives/urls.py
from django.urls import path

from archives.views import *

app_name = 'archive'

urlpatterns = [
    path('', act_index, name='act-index'),
    path('act/<int:id>/detail/', act_detail, name='act-detail'),
    path('act/<int:act_id>/confirm/', act_confirm, name='act-confirm'),
    path('act/<int:act_id>/custom/', act_custom, name='act-custom'),
    path('act/<int:pk>/edit/', act_edit, name='act-edit'),
    path('act/<int:pk>/delete/', act_delete, name='act-delete'),

    path('custom/faculty/', custom_faculty, name='custom-faculty'),
    path('custom/faculty/<int:pk>/edit/', custom_faculty_edit, name='custom-faculty-edit'),

    path('ocr/', ocr_view, name='ocr'),
    path('detect/ocr/', detect_act_image, name='detect-ocr'),
]

bsadmin/urls.py
from django.urls import path

from bsadmin.views import *

app_name = 'bsadmin'
urlpatterns = [
    path('', faculty_index, name='index'),
    path('transcript/search/', at_search, name='at-search'),
    path('transcript/faculty/<int:faculty_id>/category/', faculty_transcript_category,
         name='faculty-transcript-category'),
    path('transcript/<int:faculty_id>/reports/', ReportFacultyRegAcademicTranscript.as_view(),
         name='faculty-academic-transcript-reports'),
    path('transcript/faculties/reports/', ReportAllFacultyRegAcademicTranscript.as_view(),
         name='all-faculty-academic-transcript-reports'),
    path('transcript/faculty/<int:faculty_id>/category/<category_id>/', registration_academic_transcript_faculty,
         name='academic-transcript-faculty-registration'),

    path('transcript/student/', registration_academic_transcript_student, name='academic-transcript-student'),
    path('faculty/', faculty, name='faculty'),
    path('faculty/<int:faculty_id>/specialities/', speciality, name='speciality'),

    path('transcript/save-student/', save_academic_transcript_student, name='save-student-academic-transcript'),

    path('faculty/update/<int:id>/transcript/', update_faculty_transcript, name='update_faculty_transcript'),
    path('faculty/delete/<int:id>/transcript/', delete_faculty_transcript, name='delete_faculty_transcript'),
    path('faculty/delete/<int:id>/history/transcript/', delete_registry_faculty_transcript,
         name='delete_faculty_history_transcript'),

    path('fail/transcript/', fail_transcript, name='fail_transcript'),
    path('faculty/specialities/', specialities_by_faculty, name='specialities-faculty'),

]

core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bsheet/', include('bsadmin.urls'), name='bsheet'),
    path('stepper/', include('stepper.urls'), name='stepper'),
    path('integrator/', include('integrator.urls'), name='integrator'),
    path('archive/', include('archives.urls'), name='archive'),
    path('', include('student.urls'), name='student'),
]
# urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]
if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)), ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

integrator/urls.py
from django.urls import path

from integrator.views import *

app_name = 'integrator'
urlpatterns = [
    path('', integrator_index, name='index'),

    path('login/', sign_in_teacher_view, name='next-teacher-login'),
    path('logout/', sign_out_teacher_view, name='next-teacher-logout'),
]

stepper/urls.py
from django.urls import path

from stepper.views import *

app_name = 'stepper'
urlpatterns = [
    path('', route, name='route'),
    path('students/', cs_index, name='index'),
    path('student/<int:myedu_id>/detail/', cs_detail, name='cs-detail'),
    path('student/<int:myedu_id>/force/', cs_force, name='cs-force'),
    path('student/<int:myedu_id>/order/done/', order_done, name='order-done'),
    path('student/<int:myedu_id>/request/', request_cs, name='request-cs'),
    path('student/<int:id>/step/remove/', step_remove, name='step-remove'),
    path('student/<int:id>/step/<int:trajectory_id>/rating/', step_rating, name='step-rating'),

    path('stage/employee/', stage_employee, name='stage-employee'),
    path('stage/employee/create/', stage_employee_create, name='stage-employee-create'),
    path('stage/employee/<int:pk>/update/', stage_employee_update, name='stage-employee-update'),

    path('cs/', cs, name='cs'),
    path('cs/status/', cs_status, name='cs-status'),
    path('cs/delete/', cs_delete, name='cs-delete'),
    path('cs/done/', cs_done, name='cs-done'),
    path('cs/issuance/', cs_issuance, name='cs-issuance'),
    path('cs/<int:stage>/stage/', cs_debt_stage, name='cs-stage'),
    path('cs/<int:cs_id>/report/', cs_report, name='cs-report'),
    path('cs/<int:cs_id>/step/undo/', cs_step_undo, name='cs-step-undo'),
    path('cs/<int:myedu_id>/history/<int:cs_id>/detail/', cs_history, name='cs-history'),
    path('cs/<int:cs_id>/history/detail/', cs_history_detail, name='cs-history-detail'),

    path('spec/', spec, name='spec'),
    path('spec/<int:id>/<int:myedu_id>/student/', spec_part, name='spec-part'),
    path('spec/diploma/', spec_diploma, name='spec-diploma'),
    path('spec/history/', spec_history, name='spec-history'),
    path('spec/report/', spec_report, name='spec-report'),
    path('spec/avn/', spec_avn, name='spec-avn'),
    path('spec/students/', spec_students, name='spec-students'),
    path('spec/<int:id>/<int:myedu_id>/sync/', spec_sync, name='spec-sync'),
    path('spec/<int:id>/<int:myedu_id>/student/double', spec_part_double, name='spec-part-double'),
    path('spec/<int:id>/<int:myedu_id>/student/remove/', spec_part_remove, name='spec-part-remove'),

    path('archive/', archive, name='archive'),
    path('archive/history/', archive_history, name='archive-history'),
    path('archive/avn/', archive_avn, name='archive-avn'),
    path('archive/<int:id>/<int:myedu_id>/student/', archive_part, name='archive-part'),
    path('archive/<int:id>/<int:myedu_id>/student/remove/', archive_part_remove, name='archive-part-remove'),

    path('debts/', debts, name='debts'),
    path('debts/history/', debts_history, name='debts-history'),
    path('debts/<int:id>/comment/', debts_comment, name='debts-comment'),
    path('debts/<int:id>/comment/history/', debts_comment_history, name='debts-comment-history'),

    path("api/check_clearance_sheet/", check_clearance_sheet, name="check_clearance_sheet"),
    path("api/create_clearance_sheet/", create_clearance_sheet, name="create_clearance_sheet"),

    path("api/specailities/", load_specialities, name="load-specialities"),
    path("api/create-diploma/", diploma_create_ajax, name="create-diploma"),

    path('api/issuance-delete/', cs_issuance_delete, name='issuance-delete'),

    path("teachers/", teachers, name="teachers"),
    path("teacher/<str:myedu_id>/cs/", teacher_cs_detail, name="teacher-cs-detail"),
    path('teachers/cs/', teachers_cs, name='teachers-cs'),
    path('teachers/debts/', teacher_debts, name='teacher-debts'),
    path('teachers/debts/<int:id>/comment/', teacher_debt_comments, name='teacher-debt-comments'),

    path('check/<str:qr_id>/qrcode/status/', qr_code_status, name='qr-code-status')
]

templates/component/footer.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
{#<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"#}
{#        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"#}
{#        crossorigin="anonymous"></script>#}
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"#}
{#        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"#}
{#        crossorigin="anonymous"></script>#}
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>#}
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

<script type="text/javascript" src="{% static 'js/ajax.js' %}"></script>
<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>

templates/component/header.html
{% load static %}
{#<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"#}
{#      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">#}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"/>
{#<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"/>#}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>

<link rel="stylesheet" href="{% static 'css/style.css' %}"/>

templates/component/navbar.html
{% load i18n %}

<ul>
    {% if request.user.is_authenticated %}
        {% if request.session.access == "bsadmin" %}
            <li class="{% if navbar == 'index' %}active{% endif %}">
                <a href="{% url 'bsadmin:index' %}"><i
                        class="fas fa-home"></i><span>{% trans 'Регистрация' %}</span></a>
            </li>
            {% if CUSTOM_ROLES.SPEC in DB_ROLES %}
                <li class="{% if navbar == 'faculty' %}active{% endif %}">
                    <a href="{% url 'bsadmin:faculty' %}"><i
                            class="fas fa-cloud-download-alt"></i><span>{% trans 'Факультеты' %}</span></a>
                </li>
                <li class="{% if navbar == 'at-register-student' %}active{% endif %}">
                    <a href="{% url 'bsadmin:academic-transcript-student' %}"><i
                            class="fas fa-registered"></i><span>{% trans 'Выдача' %}</span></a>
                </li>
                <li class="{% if navbar == 'at-search' %}active{% endif %}">
                    <a href="{% url 'bsadmin:at-search' %}"><i
                            class="fas fa-search"></i><span>{% trans 'Поиск' %}</span></a>
                </li>
            {% endif %}
        {% elif request.session.access == "stepper" %}
            {% if CUSTOM_ROLES.STADMIN in DB_ROLES %}
                <li class="{% if navbar == 'stepper' %}active{% endif %}">
                    <a href="{% url 'stepper:index' %}">
                        <i class="fas fa-money-check"></i><span> {% trans 'MyEDU' %}</span>
                    </a>
                </li>
                <li class="{% if navbar == 'cs' %}active{% endif %}">
                    <a href="{% url 'stepper:cs' %}">
                        <i class="fas fa-tasks"></i><span> {% trans 'Обходной' %}</span>
                    </a>
                </li>
                <li class="{% if navbar == 'cs-done' %}active{% endif %}">
                    <a href="{% url 'stepper:cs-done' %}">
                        <i class="fas fa-check-square"></i><span>{% trans 'Завершенные' %}</span>
                    </a>
                </li>
                <li class="{% if navbar == 'issuance' %}active{% endif %}">
                    <a href="{% url 'stepper:cs-issuance' %}">
                        <i class="fas fa-book"></i><span> {% trans 'Документы' %}</span>
                    </a>
                </li>
                <li class="{% if navbar == 'roles' %}active{% endif %}">
                    <a href="{% url 'stepper:stage-employee' %}">
                        <i class="fas fa-link"></i><span> {% trans 'Сотрудники' %}</span>
                    </a>
                </li>

            {% elif CUSTOM_ROLES.STDEBT in DB_ROLES %}
                <li class="{% if navbar == 'stepper' %}active{% endif %}">
                    <a href="{% url 'stepper:debts' %}">
                        <i class="far fa-credit-card"></i><span> {% trans 'Студенты' %}</span>
                    </a>
                </li>
                <li class="{% if navbar == 'stepper-history' %}active{% endif %}">
                    <a href="{% url 'stepper:debts-history' %}">
                        <i class="fas fa-history"></i><span>{% trans 'История' %}</span>
                    </a>
                </li>
            {% elif CUSTOM_ROLES.STSPEC in DB_ROLES %}
                <li class="{% if navbar == 'spec' %}active{% endif %}">
                    <a href="{% url 'stepper:spec' %}">
                        <i class="fas fa-paper-plane"></i><span> {% trans 'Выдача' %}</span>
                    </a>
                </li>
                <li class="{% if navbar == 'spec-history' %}active{% endif %}">
                    <a href="{% url 'stepper:spec-history' %}">
                        <i class="fas fa-history"></i><span> {% trans 'История' %}</span>
                    </a>
                </li>
                <li class="{% if navbar == 'spec-report' %}active{% endif %}">
                    <a href="{% url 'stepper:spec-report' %}">
                        <i class="fas fa-file-pdf"></i><span> {% trans 'Отчет' %}</span>
                    </a>
                </li>
                <li class="{% if navbar == 'spec-students' %}active{% endif %}">
                    <a href="{% url 'stepper:spec-students' %}">
                        <i class="fas fa-id-card"></i><span> {% trans 'Дипломы' %}</span>
                    </a>
                </li>
{#                <li class="{% if navbar == 'spec-avn' %}active{% endif %}">#}
{#                    <a href="{% url 'stepper:spec-avn' %}">#}
{#                        <i class="fas fa-file-download"></i><span> {% trans 'АВН' %}</span>#}
{#                    </a>#}
{#                </li>#}
            {% elif CUSTOM_ROLES.STARCHIVE in DB_ROLES %}
                <li class="{% if navbar == 'archive' %}active{% endif %}">
                    <a href="{% url 'stepper:archive' %}">
                        <i class="fas fa-paper-plane"></i><span> {% trans 'Выдача' %}</span>
                    </a>
                </li>
                <li class="{% if navbar == 'archive-history' %}active{% endif %}">
                    <a href="{% url 'stepper:archive-history' %}">
                        <i class="fas fa-history"></i><span> {% trans 'История' %}</span>
                    </a>
                </li>
                <li class="{% if navbar == 'archive-index' %}active{% endif %}">
                    <a href="{% url 'archive:act-index' %}">
                        <i class="fab fa-react"></i><span> {% trans 'Акты' %}</span>
                    </a>
                </li>
{#                <li class="{% if navbar == 'archive-avn' %}active{% endif %}">#}
{#                    <a href="{% url 'stepper:archive-avn' %}">#}
{#                        <i class="fas fa-archive"></i><span>{% trans 'АВН' %}</span>#}
{#                    </a>#}
{#                </li>#}
            {% endif %}
            {#        {% elif request.session.access == "teacher" %}#}
            {#            {% if CUSTOM_ROLES.STTEACHER in DB_ROLES %}#}
            {#                <li class="{% if navbar == 'teachers' %}active{% endif %}">#}
            {#                    <a href="{% url 'stepper:teachers' %}">#}
            {#                        <i class="fas fa-money-check"></i><span> {% trans 'Главная' %}</span>#}
            {#                    </a>#}
            {#                </li>#}
            {#            {% elif CUSTOM_ROLES.STDEBT in DB_ROLES  %}#}
            {#                <li class="{% if navbar == 'teachers' %}active{% endif %}">#}
            {#                    <a href="{% url 'stepper:teacher-debts' %}">#}
            {#                        <i class="far fa-credit-card"></i><span> {% trans 'Студенты' %}</span>#}
            {#                    </a>#}
            {#                </li>#}
            {#            {% endif %}#}
        {% endif %}
        <li class="{% if navbar == 'integrator' %}active{% endif %}">
            <a href="{% url 'integrator:index' %}">
                <i class="fas fa-project-diagram"></i><span>{% trans 'Модули' %}</span>
            </a>
        </li>
        <li>
            <a href="{% url 'integrator:next-teacher-logout' %}">
                <i class="fas fa-sign-out-alt"></i><span>{% trans 'Выход' %}</span>
            </a>
        </li>
    {% else %}
        <li class="{% if navbar == 'teacher-next-login' %}active{% endif %}">
            <a href="{% url 'integrator:next-teacher-login' %}"><i
                    class="fas fa-sign-in-alt"></i><span>{% trans 'Войти' %}</span></a>
        </li>
    {% endif %}
</ul>